apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - name: jenkin1
        image: deepakvakkala123/kubernetesdeployment:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-servicex
spec:
  type : NodePort
  selector:
    app: my-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
