---
apiVersion: v1
kind: Secret
metadata:
  name: booksdb-secrets
data:
  POSTGRES_USER: ZGVlcGFrdXNlcg== #deepakuser
  POSTGRES_PASSWORD: cGFzc3dvcmQ= #password
  POSTGRES_DB: Ym9va3NkYg== #booksdb
---
apiVersion: v1
kind: Secret
metadata:
  name: usersdb-secrets
data:
  POSTGRES_USER: ZGVlcGFrdXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: dXNlcmRi
---