---
apiVersion: v1
kind: Secret
metadata:
  name: booksdb-secrets
data:
  POSTGRES_USER: ZGVlcGFrdXNlcg== #deepakuser
  POSTGRES_PASSWORD: cGFzc3dvcmQ= #password
  POSTGRES_DB: Ym9va3NkYg== #booksdb
---
apiVersion: v1
kind: Secret
metadata:
  name: usersdb-secrets
data:
  POSTGRES_USER: ZGVlcGFrdXNlcg== #deepakuser
  POSTGRES_PASSWORD: cGFzc3dvcmQ= #password
  POSTGRES_DB: dXNlcmRi #usersdb
---
apiVersion: v1
kind: Secret
metadata:
  name: users-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RlZXBha3VzZXI6cGFzc3dvcmRAYm9va3NkYi0wLmJvb2tzZGItc3ZjOjU0MzIvYm9va3NkYg==
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
---